name: traductor_creole
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.8.3
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  speech_to_text: ^7.0.0
  flutter_tts: ^3.8.5
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  # Las líneas de abajo deben tener exactamente 2 espacios de sangría
  uses-material-design: true
  
  # La sección de assets debe estar alineada con uses-material-design
  assets:
    - .env
    - assets/images/google_logo.png # <--- Ahora está perfectamente alineado con el guion de arriba
    - assets/images/icon_app.png   # <--- Necesario para que funcione flutter_launcher_icons

# Esta sección debe estar al mismo nivel que 'flutter:' (sin espacios al inicio)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_app.png"
  remove_alpha_ios: true