name: traductor_creole
description: "Proyecto de traductor Criollo con backend en Supabase."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  
  # Backend y Autenticación
  supabase_flutter: ^2.6.0
  auth0_flutter: ^1.4.0      # <--- ESTA FALTABA
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.8.3
  
  # Utilidades
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8

  # Funciones del Traductor
  speech_to_text: ^7.0.0
  flutter_tts: ^3.8.5

  # Iconos de la App
  flutter_launcher_icons: ^0.13.1
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/google_logo.png
    - assets/images/logo_app2.png
    - assets/images/logo_app.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_app2.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo_app2.png"